"""Create reviews table

Revision ID: 152b1373d5c7
Revises: e76d72788f22
Create Date: 2025-10-21 00:04:49.066064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152b1373d5c7'
down_revision: Union[str, Sequence[str], None] = 'e76d72788f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=1, scale=1),
               type_=sa.Numeric(precision=2, scale=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.NUMERIC(precision=1, scale=1),
               nullable=False)
    # ### end Alembic commands ###
