"""Delete tables products, reviews

Revision ID: ef5f84450127
Revises: 1ee0020e255c
Create Date: 2025-10-21 00:46:45.884642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5f84450127'
down_revision: Union[str, Sequence[str], None] = '1ee0020e255c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM reviews")
    op.execute("DELETE FROM products")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
